/* Generated by Strada Bootstrap Compiler */
/* Package: Math::Utils */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

/* @INC paths: */
/*   lib */

StradaValue* Math_Utils_add(StradaValue* a, StradaValue* b);
StradaValue* Math_Utils_subtract(StradaValue* a, StradaValue* b);
StradaValue* Math_Utils_multiply(StradaValue* a, StradaValue* b);
StradaValue* Math_Utils_square(StradaValue* n);
StradaValue* Math_Utils_factorial(StradaValue* n);

StradaValue* Math_Utils_add(StradaValue* a, StradaValue* b) {
    return strada_new_num(strada_to_num(a) + strada_to_num(b));
}

StradaValue* Math_Utils_subtract(StradaValue* a, StradaValue* b) {
    return strada_new_num(strada_to_num(a) - strada_to_num(b));
}

StradaValue* Math_Utils_multiply(StradaValue* a, StradaValue* b) {
    return strada_new_num(strada_to_num(a) * strada_to_num(b));
}

StradaValue* Math_Utils_square(StradaValue* n) {
    return strada_new_num(strada_to_num(n) * strada_to_num(n));
}

StradaValue* Math_Utils_factorial(StradaValue* n) {
    if (strada_to_bool(strada_new_int(strada_to_num(n) <= strada_to_num(strada_new_int(1))))) {
        return 1;
    }
    return strada_new_num(strada_to_num(n) * strada_to_num(Math_Utils_factorial(strada_new_num(strada_to_num(n) - strada_to_num(strada_new_int(1))))));
}

