/* Generated by Strada Bootstrap Compiler */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

/* @INC paths: */
/*   lib */

StradaValue* NODE_PROGRAM(void);
StradaValue* NODE_FUNC(void);
StradaValue* NODE_PARAM(void);
StradaValue* NODE_BLOCK(void);
StradaValue* NODE_VAR_DECL(void);
StradaValue* NODE_IF_STMT(void);
StradaValue* NODE_WHILE_STMT(void);
StradaValue* NODE_FOR_STMT(void);
StradaValue* NODE_RETURN_STMT(void);
StradaValue* NODE_EXPR_STMT(void);
StradaValue* NODE_BINARY_OP(void);
StradaValue* NODE_UNARY_OP(void);
StradaValue* NODE_CALL(void);
StradaValue* NODE_VARIABLE(void);
StradaValue* NODE_INT_LITERAL(void);
StradaValue* NODE_NUM_LITERAL(void);
StradaValue* NODE_STR_LITERAL(void);
StradaValue* NODE_ASSIGN(void);
StradaValue* NODE_SUBSCRIPT(void);
StradaValue* NODE_HASH_ACCESS(void);
StradaValue* NODE_REF(void);
StradaValue* NODE_DEREF_HASH(void);
StradaValue* NODE_DEREF_ARRAY(void);
StradaValue* NODE_DEREF_SCALAR(void);
StradaValue* NODE_ANON_HASH(void);
StradaValue* NODE_ANON_ARRAY(void);
StradaValue* TYPE_INT(void);
StradaValue* TYPE_NUM(void);
StradaValue* TYPE_STR(void);
StradaValue* TYPE_ARRAY(void);
StradaValue* TYPE_HASH(void);
StradaValue* TYPE_SCALAR(void);
StradaValue* TYPE_VOID(void);
StradaValue* ast_new_node(StradaValue* type);
StradaValue* ast_new_program(void);
void ast_add_function(StradaValue* program, StradaValue* fn);
StradaValue* ast_new_function(StradaValue* name, StradaValue* return_type);
void ast_add_param(StradaValue* fn, StradaValue* param);
StradaValue* ast_new_param(StradaValue* name, StradaValue* param_type, StradaValue* sigil);
StradaValue* ast_new_block(void);
void ast_add_statement(StradaValue* block, StradaValue* stmt);
StradaValue* ast_new_var_decl(StradaValue* name, StradaValue* var_type, StradaValue* sigil);
StradaValue* ast_new_if_stmt(StradaValue* condition, StradaValue* then_block);
void ast_add_elsif(StradaValue* if_stmt, StradaValue* condition, StradaValue* block);
StradaValue* ast_new_while_stmt(StradaValue* condition, StradaValue* body);
StradaValue* ast_new_for_stmt(StradaValue* init, StradaValue* cond, StradaValue* update, StradaValue* body);
StradaValue* ast_new_return_stmt(StradaValue* value);
StradaValue* ast_new_expr_stmt(StradaValue* expr);
StradaValue* ast_new_binary_op(StradaValue* op, StradaValue* left, StradaValue* right);
StradaValue* ast_new_unary_op(StradaValue* op, StradaValue* operand);
StradaValue* ast_new_call(StradaValue* name);
void ast_add_arg(StradaValue* call, StradaValue* arg);
StradaValue* ast_new_variable(StradaValue* name, StradaValue* sigil);
StradaValue* ast_new_int_literal(StradaValue* value);
StradaValue* ast_new_num_literal(StradaValue* value);
StradaValue* ast_new_str_literal(StradaValue* value);
StradaValue* ast_new_assign(StradaValue* op, StradaValue* target, StradaValue* value);
StradaValue* ast_new_subscript(StradaValue* arr, StradaValue* index);
StradaValue* ast_new_hash_access(StradaValue* hash_var, StradaValue* key);
StradaValue* ast_new_ref(StradaValue* target, StradaValue* ref_type);
StradaValue* ast_new_deref_hash(StradaValue* ref_expr, StradaValue* key);
StradaValue* ast_new_deref_array(StradaValue* ref_expr, StradaValue* index);
StradaValue* ast_new_deref_scalar(StradaValue* ref_expr);
StradaValue* ast_new_anon_hash(void);
void ast_add_hash_pair(StradaValue* hash_node, StradaValue* key, StradaValue* value);
StradaValue* ast_new_anon_array(void);
void ast_add_array_elem(StradaValue* arr_node, StradaValue* elem);
StradaValue* ast_type_name(StradaValue* type);
StradaValue* ast_data_type_name(StradaValue* type);

StradaValue* NODE_PROGRAM(void) {
    return 1;
}

StradaValue* NODE_FUNC(void) {
    return 2;
}

StradaValue* NODE_PARAM(void) {
    return 3;
}

StradaValue* NODE_BLOCK(void) {
    return 4;
}

StradaValue* NODE_VAR_DECL(void) {
    return 5;
}

StradaValue* NODE_IF_STMT(void) {
    return 6;
}

StradaValue* NODE_WHILE_STMT(void) {
    return 7;
}

StradaValue* NODE_FOR_STMT(void) {
    return 8;
}

StradaValue* NODE_RETURN_STMT(void) {
    return 9;
}

StradaValue* NODE_EXPR_STMT(void) {
    return 10;
}

StradaValue* NODE_BINARY_OP(void) {
    return 11;
}

StradaValue* NODE_UNARY_OP(void) {
    return 12;
}

StradaValue* NODE_CALL(void) {
    return 13;
}

StradaValue* NODE_VARIABLE(void) {
    return 14;
}

StradaValue* NODE_INT_LITERAL(void) {
    return 15;
}

StradaValue* NODE_NUM_LITERAL(void) {
    return 16;
}

StradaValue* NODE_STR_LITERAL(void) {
    return 17;
}

StradaValue* NODE_ASSIGN(void) {
    return 18;
}

StradaValue* NODE_SUBSCRIPT(void) {
    return 19;
}

StradaValue* NODE_HASH_ACCESS(void) {
    return 20;
}

StradaValue* NODE_REF(void) {
    return 21;
}

StradaValue* NODE_DEREF_HASH(void) {
    return 22;
}

StradaValue* NODE_DEREF_ARRAY(void) {
    return 23;
}

StradaValue* NODE_DEREF_SCALAR(void) {
    return 24;
}

StradaValue* NODE_ANON_HASH(void) {
    return 25;
}

StradaValue* NODE_ANON_ARRAY(void) {
    return 26;
}

StradaValue* TYPE_INT(void) {
    return 1;
}

StradaValue* TYPE_NUM(void) {
    return 2;
}

StradaValue* TYPE_STR(void) {
    return 3;
}

StradaValue* TYPE_ARRAY(void) {
    return 4;
}

StradaValue* TYPE_HASH(void) {
    return 5;
}

StradaValue* TYPE_SCALAR(void) {
    return 6;
}

StradaValue* TYPE_VOID(void) {
    return 7;
}

StradaValue* ast_new_node(StradaValue* type) {
    StradaValue *node = strada_hash_new();
    strada_hash_set(node->value.hv, strada_to_str(strada_new_str("type")), type);
    return strada_new_ref(node, '%');
}

StradaValue* ast_new_program(void) {
    StradaValue *node = ast_new_node(NODE_PROGRAM());
    StradaValue *funcs = strada_hash_new();
    StradaValue *structs = strada_hash_new();
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("functions")), strada_new_ref(funcs, '@'));
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("structs")), strada_new_ref(structs, '@'));
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("function_count")), strada_new_int(0));
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("struct_count")), strada_new_int(0));
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("package_name")), strada_new_str(""));
    return node;
}

void ast_add_function(StradaValue* program, StradaValue* fn) {
    StradaValue *funcs = strada_hash_get(strada_deref_hash(program), strada_to_str(strada_new_str("functions")));
    (strada_array_push(funcs->value.av, fn), strada_new_undef());
    strada_hash_set(strada_deref_hash(program), strada_to_str(strada_new_str("function_count")), strada_new_num(strada_to_num(strada_hash_get(strada_deref_hash(program), strada_to_str(strada_new_str("function_count")))) + strada_to_num(strada_new_int(1))));
}

StradaValue* ast_new_function(StradaValue* name, StradaValue* return_type) {
    StradaValue *node = ast_new_node(NODE_FUNC());
    StradaValue *params = strada_hash_new();
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("name")), name);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("return_type")), return_type);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("params")), strada_new_ref(params, '@'));
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("param_count")), strada_new_int(0));
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("body")), strada_new_int(0));
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("is_extern")), strada_new_int(0));
    return node;
}

void ast_add_param(StradaValue* fn, StradaValue* param) {
    StradaValue *params = strada_hash_get(strada_deref_hash(fn), strada_to_str(strada_new_str("params")));
    (strada_array_push(params->value.av, param), strada_new_undef());
    strada_hash_set(strada_deref_hash(fn), strada_to_str(strada_new_str("param_count")), strada_new_num(strada_to_num(strada_hash_get(strada_deref_hash(fn), strada_to_str(strada_new_str("param_count")))) + strada_to_num(strada_new_int(1))));
}

StradaValue* ast_new_param(StradaValue* name, StradaValue* param_type, StradaValue* sigil) {
    StradaValue *node = ast_new_node(NODE_PARAM());
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("name")), name);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("param_type")), param_type);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("sigil")), sigil);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("is_optional")), strada_new_int(0));
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("default_value")), strada_new_int(0));
    return node;
}

StradaValue* ast_new_block(void) {
    StradaValue *node = ast_new_node(NODE_BLOCK());
    StradaValue *stmts = strada_hash_new();
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("statements")), strada_new_ref(stmts, '@'));
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("statement_count")), strada_new_int(0));
    return node;
}

void ast_add_statement(StradaValue* block, StradaValue* stmt) {
    StradaValue *stmts = strada_hash_get(strada_deref_hash(block), strada_to_str(strada_new_str("statements")));
    (strada_array_push(stmts->value.av, stmt), strada_new_undef());
    strada_hash_set(strada_deref_hash(block), strada_to_str(strada_new_str("statement_count")), strada_new_num(strada_to_num(strada_hash_get(strada_deref_hash(block), strada_to_str(strada_new_str("statement_count")))) + strada_to_num(strada_new_int(1))));
}

StradaValue* ast_new_var_decl(StradaValue* name, StradaValue* var_type, StradaValue* sigil) {
    StradaValue *node = ast_new_node(NODE_VAR_DECL());
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("name")), name);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("var_type")), var_type);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("sigil")), sigil);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("init")), strada_new_int(0));
    return node;
}

StradaValue* ast_new_if_stmt(StradaValue* condition, StradaValue* then_block) {
    StradaValue *node = ast_new_node(NODE_IF_STMT());
    StradaValue *elsif_conds = strada_hash_new();
    StradaValue *elsif_blocks = strada_hash_new();
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("condition")), condition);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("then_block")), then_block);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("elsif_conditions")), strada_new_ref(elsif_conds, '@'));
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("elsif_blocks")), strada_new_ref(elsif_blocks, '@'));
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("elsif_count")), strada_new_int(0));
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("else_block")), strada_new_int(0));
    return node;
}

void ast_add_elsif(StradaValue* if_stmt, StradaValue* condition, StradaValue* block) {
    StradaValue *conds = strada_hash_get(strada_deref_hash(if_stmt), strada_to_str(strada_new_str("elsif_conditions")));
    StradaValue *blocks = strada_hash_get(strada_deref_hash(if_stmt), strada_to_str(strada_new_str("elsif_blocks")));
    (strada_array_push(conds->value.av, condition), strada_new_undef());
    (strada_array_push(blocks->value.av, block), strada_new_undef());
    strada_hash_set(strada_deref_hash(if_stmt), strada_to_str(strada_new_str("elsif_count")), strada_new_num(strada_to_num(strada_hash_get(strada_deref_hash(if_stmt), strada_to_str(strada_new_str("elsif_count")))) + strada_to_num(strada_new_int(1))));
}

StradaValue* ast_new_while_stmt(StradaValue* condition, StradaValue* body) {
    StradaValue *node = ast_new_node(NODE_WHILE_STMT());
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("condition")), condition);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("body")), body);
    return node;
}

StradaValue* ast_new_for_stmt(StradaValue* init, StradaValue* cond, StradaValue* update, StradaValue* body) {
    StradaValue *node = ast_new_node(NODE_FOR_STMT());
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("init")), init);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("condition")), cond);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("update")), update);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("body")), body);
    return node;
}

StradaValue* ast_new_return_stmt(StradaValue* value) {
    StradaValue *node = ast_new_node(NODE_RETURN_STMT());
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("value")), value);
    return node;
}

StradaValue* ast_new_expr_stmt(StradaValue* expr) {
    StradaValue *node = ast_new_node(NODE_EXPR_STMT());
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("expr")), expr);
    return node;
}

StradaValue* ast_new_binary_op(StradaValue* op, StradaValue* left, StradaValue* right) {
    StradaValue *node = ast_new_node(NODE_BINARY_OP());
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("op")), op);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("left")), left);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("right")), right);
    return node;
}

StradaValue* ast_new_unary_op(StradaValue* op, StradaValue* operand) {
    StradaValue *node = ast_new_node(NODE_UNARY_OP());
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("op")), op);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("operand")), operand);
    return node;
}

StradaValue* ast_new_call(StradaValue* name) {
    StradaValue *node = ast_new_node(NODE_CALL());
    StradaValue *args = strada_hash_new();
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("name")), name);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("args")), strada_new_ref(args, '@'));
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("arg_count")), strada_new_int(0));
    return node;
}

void ast_add_arg(StradaValue* call, StradaValue* arg) {
    StradaValue *args = strada_hash_get(strada_deref_hash(call), strada_to_str(strada_new_str("args")));
    (strada_array_push(args->value.av, arg), strada_new_undef());
    strada_hash_set(strada_deref_hash(call), strada_to_str(strada_new_str("arg_count")), strada_new_num(strada_to_num(strada_hash_get(strada_deref_hash(call), strada_to_str(strada_new_str("arg_count")))) + strada_to_num(strada_new_int(1))));
}

StradaValue* ast_new_variable(StradaValue* name, StradaValue* sigil) {
    StradaValue *node = ast_new_node(NODE_VARIABLE());
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("name")), name);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("sigil")), sigil);
    return node;
}

StradaValue* ast_new_int_literal(StradaValue* value) {
    StradaValue *node = ast_new_node(NODE_INT_LITERAL());
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("value")), value);
    return node;
}

StradaValue* ast_new_num_literal(StradaValue* value) {
    StradaValue *node = ast_new_node(NODE_NUM_LITERAL());
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("value")), value);
    return node;
}

StradaValue* ast_new_str_literal(StradaValue* value) {
    StradaValue *node = ast_new_node(NODE_STR_LITERAL());
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("value")), value);
    return node;
}

StradaValue* ast_new_assign(StradaValue* op, StradaValue* target, StradaValue* value) {
    StradaValue *node = ast_new_node(NODE_ASSIGN());
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("op")), op);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("target")), target);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("value")), value);
    return node;
}

StradaValue* ast_new_subscript(StradaValue* arr, StradaValue* index) {
    StradaValue *node = ast_new_node(NODE_SUBSCRIPT());
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("array")), arr);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("index")), index);
    return node;
}

StradaValue* ast_new_hash_access(StradaValue* hash_var, StradaValue* key) {
    StradaValue *node = ast_new_node(NODE_HASH_ACCESS());
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("hash")), hash_var);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("key")), key);
    return node;
}

StradaValue* ast_new_ref(StradaValue* target, StradaValue* ref_type) {
    StradaValue *node = ast_new_node(NODE_REF());
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("target")), target);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("ref_type")), ref_type);
    return node;
}

StradaValue* ast_new_deref_hash(StradaValue* ref_expr, StradaValue* key) {
    StradaValue *node = ast_new_node(NODE_DEREF_HASH());
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("ref")), ref_expr);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("key")), key);
    return node;
}

StradaValue* ast_new_deref_array(StradaValue* ref_expr, StradaValue* index) {
    StradaValue *node = ast_new_node(NODE_DEREF_ARRAY());
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("ref")), ref_expr);
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("index")), index);
    return node;
}

StradaValue* ast_new_deref_scalar(StradaValue* ref_expr) {
    StradaValue *node = ast_new_node(NODE_DEREF_SCALAR());
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("ref")), ref_expr);
    return node;
}

StradaValue* ast_new_anon_hash(void) {
    StradaValue *node = ast_new_node(NODE_ANON_HASH());
    StradaValue *keys = strada_hash_new();
    StradaValue *values = strada_hash_new();
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("keys")), strada_new_ref(keys, '@'));
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("values")), strada_new_ref(values, '@'));
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("pair_count")), strada_new_int(0));
    return node;
}

void ast_add_hash_pair(StradaValue* hash_node, StradaValue* key, StradaValue* value) {
    StradaValue *keys = strada_hash_get(strada_deref_hash(hash_node), strada_to_str(strada_new_str("keys")));
    StradaValue *values = strada_hash_get(strada_deref_hash(hash_node), strada_to_str(strada_new_str("values")));
    (strada_array_push(keys->value.av, key), strada_new_undef());
    (strada_array_push(values->value.av, value), strada_new_undef());
    strada_hash_set(strada_deref_hash(hash_node), strada_to_str(strada_new_str("pair_count")), strada_new_num(strada_to_num(strada_hash_get(strada_deref_hash(hash_node), strada_to_str(strada_new_str("pair_count")))) + strada_to_num(strada_new_int(1))));
}

StradaValue* ast_new_anon_array(void) {
    StradaValue *node = ast_new_node(NODE_ANON_ARRAY());
    StradaValue *elems = strada_hash_new();
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("elements")), strada_new_ref(elems, '@'));
    strada_hash_set(strada_deref_hash(node), strada_to_str(strada_new_str("element_count")), strada_new_int(0));
    return node;
}

void ast_add_array_elem(StradaValue* arr_node, StradaValue* elem) {
    StradaValue *elems = strada_hash_get(strada_deref_hash(arr_node), strada_to_str(strada_new_str("elements")));
    (strada_array_push(elems->value.av, elem), strada_new_undef());
    strada_hash_set(strada_deref_hash(arr_node), strada_to_str(strada_new_str("element_count")), strada_new_num(strada_to_num(strada_hash_get(strada_deref_hash(arr_node), strada_to_str(strada_new_str("element_count")))) + strada_to_num(strada_new_int(1))));
}

StradaValue* ast_type_name(StradaValue* type) {
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_PROGRAM())))) {
        return strada_new_str("PROGRAM");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_FUNC())))) {
        return strada_new_str("FUNC");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_PARAM())))) {
        return strada_new_str("PARAM");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_BLOCK())))) {
        return strada_new_str("BLOCK");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_VAR_DECL())))) {
        return strada_new_str("VAR_DECL");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_IF_STMT())))) {
        return strada_new_str("IF_STMT");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_WHILE_STMT())))) {
        return strada_new_str("WHILE_STMT");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_FOR_STMT())))) {
        return strada_new_str("FOR_STMT");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_RETURN_STMT())))) {
        return strada_new_str("RETURN_STMT");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_EXPR_STMT())))) {
        return strada_new_str("EXPR_STMT");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_BINARY_OP())))) {
        return strada_new_str("BINARY_OP");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_UNARY_OP())))) {
        return strada_new_str("UNARY_OP");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_CALL())))) {
        return strada_new_str("CALL");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_VARIABLE())))) {
        return strada_new_str("VARIABLE");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_INT_LITERAL())))) {
        return strada_new_str("INT_LITERAL");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_NUM_LITERAL())))) {
        return strada_new_str("NUM_LITERAL");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_STR_LITERAL())))) {
        return strada_new_str("STR_LITERAL");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_ASSIGN())))) {
        return strada_new_str("ASSIGN");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_SUBSCRIPT())))) {
        return strada_new_str("SUBSCRIPT");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_HASH_ACCESS())))) {
        return strada_new_str("HASH_ACCESS");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_REF())))) {
        return strada_new_str("REF");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_DEREF_HASH())))) {
        return strada_new_str("DEREF_HASH");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_DEREF_ARRAY())))) {
        return strada_new_str("DEREF_ARRAY");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_DEREF_SCALAR())))) {
        return strada_new_str("DEREF_SCALAR");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_ANON_HASH())))) {
        return strada_new_str("ANON_HASH");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_ANON_ARRAY())))) {
        return strada_new_str("ANON_ARRAY");
    }
    return strada_new_str("UNKNOWN");
}

StradaValue* ast_data_type_name(StradaValue* type) {
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(TYPE_INT())))) {
        return strada_new_str("int");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(TYPE_NUM())))) {
        return strada_new_str("num");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(TYPE_STR())))) {
        return strada_new_str("str");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(TYPE_ARRAY())))) {
        return strada_new_str("array");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(TYPE_HASH())))) {
        return strada_new_str("hash");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(TYPE_SCALAR())))) {
        return strada_new_str("scalar");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(TYPE_VOID())))) {
        return strada_new_str("void");
    }
    return strada_new_str("unknown");
}

