/* Generated by Strada Bootstrap Compiler */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

/* @INC paths: */
/*   lib */

StradaValue* codegen_new(void);
void emit(StradaValue* cg, StradaValue* text);
void emit_line(StradaValue* cg, StradaValue* text);
void emit_indent(StradaValue* cg);
void indent(StradaValue* cg);
void dedent(StradaValue* cg);
StradaValue* type_to_c(StradaValue* type);
void gen_expression(StradaValue* cg, StradaValue* expr);
void gen_block(StradaValue* cg, StradaValue* block);
void gen_statement(StradaValue* cg, StradaValue* stmt);
void gen_function(StradaValue* cg, StradaValue* fn);
void gen_program(StradaValue* cg, StradaValue* program);
StradaValue* generate(StradaValue* ast);

StradaValue* codegen_new(void) {
    StradaValue *cg = strada_hash_new();
    strada_hash_set(cg->value.hv, strada_to_str(strada_new_str("output")), strada_new_str(""));
    strada_hash_set(cg->value.hv, strada_to_str(strada_new_str("indent")), strada_new_int(0));
    return strada_new_ref(cg, '%');
}

void emit(StradaValue* cg, StradaValue* text) {
    strada_hash_set(strada_deref_hash(cg), strada_to_str(strada_new_str("output")), strada_new_str(strada_concat(strada_to_str(strada_hash_get(strada_deref_hash(cg), strada_to_str(strada_new_str("output")))), strada_to_str(text))));
}

void emit_line(StradaValue* cg, StradaValue* text) {
    emit_indent(cg);
    emit(cg, strada_new_str(strada_concat(strada_to_str(text), strada_to_str(strada_new_str("\n")))));
}

void emit_indent(StradaValue* cg) {
    StradaValue *i = strada_new_int(0);
    while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(strada_hash_get(strada_deref_hash(cg), strada_to_str(strada_new_str("indent"))))))) {
        emit(cg, strada_new_str("    "));
        i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
    }
}

void indent(StradaValue* cg) {
    strada_hash_set(strada_deref_hash(cg), strada_to_str(strada_new_str("indent")), strada_new_num(strada_to_num(strada_hash_get(strada_deref_hash(cg), strada_to_str(strada_new_str("indent")))) + strada_to_num(strada_new_int(1))));
}

void dedent(StradaValue* cg) {
    strada_hash_set(strada_deref_hash(cg), strada_to_str(strada_new_str("indent")), strada_new_num(strada_to_num(strada_hash_get(strada_deref_hash(cg), strada_to_str(strada_new_str("indent")))) - strada_to_num(strada_new_int(1))));
}

StradaValue* type_to_c(StradaValue* type) {
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(TYPE_INT())))) {
        return strada_new_str("StradaValue*");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(TYPE_NUM())))) {
        return strada_new_str("StradaValue*");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(TYPE_STR())))) {
        return strada_new_str("StradaValue*");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(TYPE_ARRAY())))) {
        return strada_new_str("StradaValue*");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(TYPE_HASH())))) {
        return strada_new_str("StradaValue*");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(TYPE_SCALAR())))) {
        return strada_new_str("StradaValue*");
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(TYPE_VOID())))) {
        return strada_new_str("void");
    }
    return strada_new_str("StradaValue*");
}

void gen_expression(StradaValue* cg, StradaValue* expr) {
    StradaValue *type = strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("type")));
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_INT_LITERAL())))) {
        emit(cg, strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(strada_new_str("strada_new_int(")), strada_to_str(strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("value"))))))), strada_to_str(strada_new_str(")")))));
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_NUM_LITERAL())))) {
        emit(cg, strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(strada_new_str("strada_new_num(")), strada_to_str(strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("value"))))))), strada_to_str(strada_new_str(")")))));
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_STR_LITERAL())))) {
        emit(cg, strada_new_str("strada_new_str(\""));
        StradaValue *val = strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("value")));
        StradaValue *i = strada_new_int(0);
        StradaValue *len = strada_new_int(strada_length(strada_to_str(val)));
        while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(len)))) {
            StradaValue *ch = strada_substr(val, strada_to_int(i), strada_to_int(strada_new_int(1)));
            if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("\n"))) == 0))) {
                emit(cg, strada_new_str("\\n"));
            } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("\t"))) == 0))) {
                emit(cg, strada_new_str("\\t"));
            } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("\r"))) == 0))) {
                emit(cg, strada_new_str("\\r"));
            } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("\""))) == 0))) {
                emit(cg, strada_new_str("\\\""));
            } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("\\"))) == 0))) {
                emit(cg, strada_new_str("\\\\"));
            } else {
                emit(cg, ch);
            }
            i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
        }
        emit(cg, strada_new_str("\")"));
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_VARIABLE())))) {
        emit(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("name"))));
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_BINARY_OP())))) {
        StradaValue *op = strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("op")));
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(op), strada_to_str(strada_new_str("+"))) == 0))) {
            emit(cg, strada_new_str("strada_new_num(strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("left"))));
            emit(cg, strada_new_str(") + strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("right"))));
            emit(cg, strada_new_str("))"));
        } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(op), strada_to_str(strada_new_str("-"))) == 0))) {
            emit(cg, strada_new_str("strada_new_num(strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("left"))));
            emit(cg, strada_new_str(") - strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("right"))));
            emit(cg, strada_new_str("))"));
        } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(op), strada_to_str(strada_new_str("*"))) == 0))) {
            emit(cg, strada_new_str("strada_new_num(strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("left"))));
            emit(cg, strada_new_str(") * strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("right"))));
            emit(cg, strada_new_str("))"));
        } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(op), strada_to_str(strada_new_str("/"))) == 0))) {
            emit(cg, strada_new_str("strada_new_num(strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("left"))));
            emit(cg, strada_new_str(") / strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("right"))));
            emit(cg, strada_new_str("))"));
        } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(op), strada_to_str(strada_new_str("."))) == 0))) {
            emit(cg, strada_new_str("strada_new_str(strada_concat(strada_to_str("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("left"))));
            emit(cg, strada_new_str("), strada_to_str("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("right"))));
            emit(cg, strada_new_str(")))"));
        } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(op), strada_to_str(strada_new_str("=="))) == 0))) {
            emit(cg, strada_new_str("strada_new_int(strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("left"))));
            emit(cg, strada_new_str(") == strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("right"))));
            emit(cg, strada_new_str("))"));
        } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(op), strada_to_str(strada_new_str("!="))) == 0))) {
            emit(cg, strada_new_str("strada_new_int(strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("left"))));
            emit(cg, strada_new_str(") != strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("right"))));
            emit(cg, strada_new_str("))"));
        } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(op), strada_to_str(strada_new_str("<"))) == 0))) {
            emit(cg, strada_new_str("strada_new_int(strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("left"))));
            emit(cg, strada_new_str(") < strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("right"))));
            emit(cg, strada_new_str("))"));
        } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(op), strada_to_str(strada_new_str(">"))) == 0))) {
            emit(cg, strada_new_str("strada_new_int(strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("left"))));
            emit(cg, strada_new_str(") > strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("right"))));
            emit(cg, strada_new_str("))"));
        } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(op), strada_to_str(strada_new_str("<="))) == 0))) {
            emit(cg, strada_new_str("strada_new_int(strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("left"))));
            emit(cg, strada_new_str(") <= strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("right"))));
            emit(cg, strada_new_str("))"));
        } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(op), strada_to_str(strada_new_str(">="))) == 0))) {
            emit(cg, strada_new_str("strada_new_int(strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("left"))));
            emit(cg, strada_new_str(") >= strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("right"))));
            emit(cg, strada_new_str("))"));
        } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(op), strada_to_str(strada_new_str("&&"))) == 0))) {
            emit(cg, strada_new_str("strada_new_int(strada_to_bool("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("left"))));
            emit(cg, strada_new_str(") && strada_to_bool("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("right"))));
            emit(cg, strada_new_str("))"));
        } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(op), strada_to_str(strada_new_str("||"))) == 0))) {
            emit(cg, strada_new_str("strada_new_int(strada_to_bool("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("left"))));
            emit(cg, strada_new_str(") || strada_to_bool("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("right"))));
            emit(cg, strada_new_str("))"));
        }
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_UNARY_OP())))) {
        StradaValue *op = strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("op")));
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(op), strada_to_str(strada_new_str("-"))) == 0))) {
            emit(cg, strada_new_str("strada_new_num(-strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("operand"))));
            emit(cg, strada_new_str("))"));
        } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(op), strada_to_str(strada_new_str("!"))) == 0))) {
            emit(cg, strada_new_str("strada_new_int(!strada_to_bool("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("operand"))));
            emit(cg, strada_new_str("))"));
        }
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_CALL())))) {
        StradaValue *name = strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("name")));
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(name), strada_to_str(strada_new_str("say"))) == 0))) {
            emit(cg, strada_new_str("strada_say("));
            if (strada_to_bool(strada_new_int(strada_to_num(strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("arg_count")))) > strada_to_num(strada_new_int(0))))) {
                StradaValue *args = strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("args")));
                gen_expression(cg, strada_array_get(strada_deref_array(args), strada_to_int(strada_new_int(0))));
            }
            emit(cg, strada_new_str(")"));
            return;
        }
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(name), strada_to_str(strada_new_str("print"))) == 0))) {
            emit(cg, strada_new_str("strada_print("));
            if (strada_to_bool(strada_new_int(strada_to_num(strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("arg_count")))) > strada_to_num(strada_new_int(0))))) {
                StradaValue *args = strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("args")));
                gen_expression(cg, strada_array_get(strada_deref_array(args), strada_to_int(strada_new_int(0))));
            }
            emit(cg, strada_new_str(")"));
            return;
        }
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(name), strada_to_str(strada_new_str("length"))) == 0))) {
            emit(cg, strada_new_str("strada_new_int(strada_length(strada_to_str("));
            StradaValue *args = strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("args")));
            gen_expression(cg, strada_array_get(strada_deref_array(args), strada_to_int(strada_new_int(0))));
            emit(cg, strada_new_str(")))"));
            return;
        }
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(name), strada_to_str(strada_new_str("substr"))) == 0))) {
            emit(cg, strada_new_str("strada_substr("));
            StradaValue *args = strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("args")));
            gen_expression(cg, strada_array_get(strada_deref_array(args), strada_to_int(strada_new_int(0))));
            emit(cg, strada_new_str(", strada_to_int("));
            gen_expression(cg, strada_array_get(strada_deref_array(args), strada_to_int(strada_new_int(1))));
            emit(cg, strada_new_str("), "));
            if (strada_to_bool(strada_new_int(strada_to_num(strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("arg_count")))) > strada_to_num(strada_new_int(2))))) {
                emit(cg, strada_new_str("strada_to_int("));
                gen_expression(cg, strada_array_get(strada_deref_array(args), strada_to_int(strada_new_int(2))));
                emit(cg, strada_new_str(")"));
            } else {
                emit(cg, strada_new_str("-1"));
            }
            emit(cg, strada_new_str(")"));
            return;
        }
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(name), strada_to_str(strada_new_str("push"))) == 0))) {
            emit(cg, strada_new_str("(strada_array_push("));
            StradaValue *args = strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("args")));
            gen_expression(cg, strada_array_get(strada_deref_array(args), strada_to_int(strada_new_int(0))));
            emit(cg, strada_new_str("->value.av, "));
            gen_expression(cg, strada_array_get(strada_deref_array(args), strada_to_int(strada_new_int(1))));
            emit(cg, strada_new_str("), strada_new_undef())"));
            return;
        }
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(name), strada_to_str(strada_new_str("size"))) == 0))) {
            emit(cg, strada_new_str("strada_new_int(strada_array_length("));
            StradaValue *args = strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("args")));
            gen_expression(cg, strada_array_get(strada_deref_array(args), strada_to_int(strada_new_int(0))));
            emit(cg, strada_new_str("->value.av))"));
            return;
        }
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(name), strada_to_str(strada_new_str("die"))) == 0))) {
            emit(cg, strada_new_str("strada_die(strada_to_str("));
            StradaValue *args = strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("args")));
            gen_expression(cg, strada_array_get(strada_deref_array(args), strada_to_int(strada_new_int(0))));
            emit(cg, strada_new_str("))"));
            return;
        }
        emit(cg, strada_new_str(strada_concat(strada_to_str(name), strada_to_str(strada_new_str("(")))));
        StradaValue *args = strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("args")));
        StradaValue *i = strada_new_int(0);
        while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("arg_count"))))))) {
            if (strada_to_bool(strada_new_int(strada_to_num(i) > strada_to_num(strada_new_int(0))))) {
                emit(cg, strada_new_str(", "));
            }
            gen_expression(cg, strada_array_get(strada_deref_array(args), strada_to_int(i)));
            i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
        }
        emit(cg, strada_new_str(")"));
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_ASSIGN())))) {
        StradaValue *op = strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("op")));
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(op), strada_to_str(strada_new_str("="))) == 0))) {
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("target"))));
            emit(cg, strada_new_str(" = "));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("value"))));
        } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(op), strada_to_str(strada_new_str("+="))) == 0))) {
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("target"))));
            emit(cg, strada_new_str(" = strada_new_num(strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("target"))));
            emit(cg, strada_new_str(") + strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("value"))));
            emit(cg, strada_new_str("))"));
        } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(op), strada_to_str(strada_new_str("-="))) == 0))) {
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("target"))));
            emit(cg, strada_new_str(" = strada_new_num(strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("target"))));
            emit(cg, strada_new_str(") - strada_to_num("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("value"))));
            emit(cg, strada_new_str("))"));
        } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(op), strada_to_str(strada_new_str(".="))) == 0))) {
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("target"))));
            emit(cg, strada_new_str(" = strada_new_str(strada_concat(strada_to_str("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("target"))));
            emit(cg, strada_new_str("), strada_to_str("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("value"))));
            emit(cg, strada_new_str(")))"));
        }
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_SUBSCRIPT())))) {
        emit(cg, strada_new_str("strada_array_get("));
        gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("array"))));
        emit(cg, strada_new_str("->value.av, strada_to_int("));
        gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("index"))));
        emit(cg, strada_new_str("))"));
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_HASH_ACCESS())))) {
        emit(cg, strada_new_str("strada_hash_get("));
        gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("hash"))));
        emit(cg, strada_new_str("->value.hv, strada_to_str("));
        gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("key"))));
        emit(cg, strada_new_str("))"));
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_REF())))) {
        emit(cg, strada_new_str("strada_new_ref("));
        gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("target"))));
        emit(cg, strada_new_str(", '"));
        emit(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("ref_type"))));
        emit(cg, strada_new_str("')"));
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_DEREF_HASH())))) {
        emit(cg, strada_new_str("strada_hash_get(strada_deref_hash("));
        gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("ref"))));
        emit(cg, strada_new_str("), strada_to_str("));
        gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("key"))));
        emit(cg, strada_new_str("))"));
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_DEREF_ARRAY())))) {
        emit(cg, strada_new_str("strada_array_get(strada_deref_array("));
        gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("ref"))));
        emit(cg, strada_new_str("), strada_to_int("));
        gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("index"))));
        emit(cg, strada_new_str("))"));
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_DEREF_SCALAR())))) {
        emit(cg, strada_new_str("strada_deref("));
        gen_expression(cg, strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("ref"))));
        emit(cg, strada_new_str(")"));
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_ANON_HASH())))) {
        emit(cg, strada_new_str(strada_concat(strada_to_str(strada_new_str("strada_anon_hash(")), strada_to_str(strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("pair_count")))))));
        StradaValue *keys = strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("keys")));
        StradaValue *values = strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("values")));
        StradaValue *i = strada_new_int(0);
        while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("pair_count"))))))) {
            emit(cg, strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(strada_new_str(", \"")), strada_to_str(strada_array_get(strada_deref_array(keys), strada_to_int(i)))))), strada_to_str(strada_new_str("\", ")))));
            gen_expression(cg, strada_array_get(strada_deref_array(values), strada_to_int(i)));
            i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
        }
        emit(cg, strada_new_str(")"));
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_ANON_ARRAY())))) {
        emit(cg, strada_new_str(strada_concat(strada_to_str(strada_new_str("strada_anon_array(")), strada_to_str(strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("element_count")))))));
        StradaValue *elems = strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("elements")));
        StradaValue *i = strada_new_int(0);
        while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(strada_hash_get(strada_deref_hash(expr), strada_to_str(strada_new_str("element_count"))))))) {
            emit(cg, strada_new_str(", "));
            gen_expression(cg, strada_array_get(strada_deref_array(elems), strada_to_int(i)));
            i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
        }
        emit(cg, strada_new_str(")"));
        return;
    }
}

void gen_block(StradaValue* cg, StradaValue* block) {
    emit(cg, strada_new_str("{\n"));
    indent(cg);
    StradaValue *stmts = strada_hash_get(strada_deref_hash(block), strada_to_str(strada_new_str("statements")));
    StradaValue *i = strada_new_int(0);
    while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(strada_hash_get(strada_deref_hash(block), strada_to_str(strada_new_str("statement_count"))))))) {
        gen_statement(cg, strada_array_get(strada_deref_array(stmts), strada_to_int(i)));
        i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
    }
    dedent(cg);
    emit_indent(cg);
    emit(cg, strada_new_str("}"));
}

void gen_statement(StradaValue* cg, StradaValue* stmt) {
    StradaValue *type = strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("type")));
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_VAR_DECL())))) {
        emit_indent(cg);
        StradaValue *sigil = strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("sigil")));
        if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(sigil), strada_to_str(strada_new_str("%"))) == 0)) || strada_to_bool(strada_new_int(strada_to_num(strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("var_type")))) == strada_to_num(TYPE_HASH())))))) {
            emit(cg, strada_new_str(strada_concat(strada_to_str(strada_new_str("StradaValue *")), strada_to_str(strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("name")))))));
            if (strada_to_bool(strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("init"))))) {
                emit(cg, strada_new_str(" = "));
                gen_expression(cg, strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("init"))));
            } else {
                emit(cg, strada_new_str(" = strada_new_hash()"));
            }
        } else if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(sigil), strada_to_str(strada_new_str("@"))) == 0)) || strada_to_bool(strada_new_int(strada_to_num(strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("var_type")))) == strada_to_num(TYPE_ARRAY())))))) {
            emit(cg, strada_new_str(strada_concat(strada_to_str(strada_new_str("StradaValue *")), strada_to_str(strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("name")))))));
            if (strada_to_bool(strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("init"))))) {
                emit(cg, strada_new_str(" = "));
                gen_expression(cg, strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("init"))));
            } else {
                emit(cg, strada_new_str(" = strada_new_array()"));
            }
        } else {
            emit(cg, strada_new_str(strada_concat(strada_to_str(strada_new_str("StradaValue *")), strada_to_str(strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("name")))))));
            if (strada_to_bool(strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("init"))))) {
                emit(cg, strada_new_str(" = "));
                gen_expression(cg, strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("init"))));
            } else {
                emit(cg, strada_new_str(" = strada_new_undef()"));
            }
        }
        emit(cg, strada_new_str(";\n"));
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_IF_STMT())))) {
        emit_indent(cg);
        emit(cg, strada_new_str("if (strada_to_bool("));
        gen_expression(cg, strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("condition"))));
        emit(cg, strada_new_str(")) "));
        gen_block(cg, strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("then_block"))));
        StradaValue *elsif_conds = strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("elsif_conditions")));
        StradaValue *elsif_blocks = strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("elsif_blocks")));
        StradaValue *i = strada_new_int(0);
        while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("elsif_count"))))))) {
            emit(cg, strada_new_str(" else if (strada_to_bool("));
            gen_expression(cg, strada_array_get(strada_deref_array(elsif_conds), strada_to_int(i)));
            emit(cg, strada_new_str(")) "));
            gen_block(cg, strada_array_get(strada_deref_array(elsif_blocks), strada_to_int(i)));
            i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
        }
        if (strada_to_bool(strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("else_block"))))) {
            emit(cg, strada_new_str(" else "));
            gen_block(cg, strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("else_block"))));
        }
        emit(cg, strada_new_str("\n"));
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_WHILE_STMT())))) {
        emit_indent(cg);
        emit(cg, strada_new_str("while (strada_to_bool("));
        gen_expression(cg, strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("condition"))));
        emit(cg, strada_new_str(")) "));
        gen_block(cg, strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("body"))));
        emit(cg, strada_new_str("\n"));
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_FOR_STMT())))) {
        emit_indent(cg);
        emit(cg, strada_new_str("for ("));
        if (strada_to_bool(strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("init"))))) {
            StradaValue *init = strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("init")));
            if (strada_to_bool(strada_new_int(strada_to_num(strada_hash_get(strada_deref_hash(init), strada_to_str(strada_new_str("type")))) == strada_to_num(NODE_VAR_DECL())))) {
                emit(cg, strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(strada_new_str("StradaValue *")), strada_to_str(strada_hash_get(strada_deref_hash(init), strada_to_str(strada_new_str("name"))))))), strada_to_str(strada_new_str(" = ")))));
                if (strada_to_bool(strada_hash_get(strada_deref_hash(init), strada_to_str(strada_new_str("init"))))) {
                    gen_expression(cg, strada_hash_get(strada_deref_hash(init), strada_to_str(strada_new_str("init"))));
                } else {
                    emit(cg, strada_new_str("strada_new_undef()"));
                }
            } else {
                gen_expression(cg, init);
            }
        }
        emit(cg, strada_new_str("; "));
        if (strada_to_bool(strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("condition"))))) {
            emit(cg, strada_new_str("strada_to_bool("));
            gen_expression(cg, strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("condition"))));
            emit(cg, strada_new_str(")"));
        }
        emit(cg, strada_new_str("; "));
        if (strada_to_bool(strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("update"))))) {
            gen_expression(cg, strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("update"))));
        }
        emit(cg, strada_new_str(") "));
        gen_block(cg, strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("body"))));
        emit(cg, strada_new_str("\n"));
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_RETURN_STMT())))) {
        emit_indent(cg);
        emit(cg, strada_new_str("return"));
        if (strada_to_bool(strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("value"))))) {
            emit(cg, strada_new_str(" "));
            if (strada_to_bool(strada_new_int(strada_to_num(strada_hash_get(strada_deref_hash(strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("value")))), strada_to_str(strada_new_str("type")))) == strada_to_num(NODE_INT_LITERAL())))) {
                emit(cg, strada_hash_get(strada_deref_hash(strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("value")))), strada_to_str(strada_new_str("value"))));
            } else {
                gen_expression(cg, strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("value"))));
            }
        }
        emit(cg, strada_new_str(";\n"));
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(NODE_EXPR_STMT())))) {
        emit_indent(cg);
        gen_expression(cg, strada_hash_get(strada_deref_hash(stmt), strada_to_str(strada_new_str("expr"))));
        emit(cg, strada_new_str(";\n"));
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(strada_new_int(100))))) {
        emit_indent(cg);
        emit(cg, strada_new_str("break;\n"));
        return;
    }
    if (strada_to_bool(strada_new_int(strada_to_num(type) == strada_to_num(strada_new_int(101))))) {
        emit_indent(cg);
        emit(cg, strada_new_str("continue;\n"));
        return;
    }
}

void gen_function(StradaValue* cg, StradaValue* fn) {
    StradaValue *ret_type = type_to_c(strada_hash_get(strada_deref_hash(fn), strada_to_str(strada_new_str("return_type"))));
    StradaValue *name = strada_hash_get(strada_deref_hash(fn), strada_to_str(strada_new_str("name")));
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(name), strada_to_str(strada_new_str("main"))) == 0))) {
        emit(cg, strada_new_str("int main(void) "));
    } else {
        emit(cg, strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(ret_type), strada_to_str(strada_new_str(" "))))), strada_to_str(name)))), strada_to_str(strada_new_str("(")))));
        StradaValue *params = strada_hash_get(strada_deref_hash(fn), strada_to_str(strada_new_str("params")));
        StradaValue *i = strada_new_int(0);
        while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(strada_hash_get(strada_deref_hash(fn), strada_to_str(strada_new_str("param_count"))))))) {
            if (strada_to_bool(strada_new_int(strada_to_num(i) > strada_to_num(strada_new_int(0))))) {
                emit(cg, strada_new_str(", "));
            }
            StradaValue *param = strada_array_get(strada_deref_array(params), strada_to_int(i));
            emit(cg, strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(type_to_c(strada_hash_get(strada_deref_hash(param), strada_to_str(strada_new_str("param_type"))))), strada_to_str(strada_new_str(" "))))), strada_to_str(strada_hash_get(strada_deref_hash(param), strada_to_str(strada_new_str("name")))))));
            i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
        }
        if (strada_to_bool(strada_new_int(strada_to_num(strada_hash_get(strada_deref_hash(fn), strada_to_str(strada_new_str("param_count")))) == strada_to_num(strada_new_int(0))))) {
            emit(cg, strada_new_str("void"));
        }
        emit(cg, strada_new_str(") "));
    }
    gen_block(cg, strada_hash_get(strada_deref_hash(fn), strada_to_str(strada_new_str("body"))));
    emit(cg, strada_new_str("\n\n"));
}

void gen_program(StradaValue* cg, StradaValue* program) {
    emit(cg, strada_new_str("/* Generated by Strada Self-Hosting Compiler */\n"));
    emit(cg, strada_new_str("#include \"strada_runtime.h\"\n"));
    emit(cg, strada_new_str("#include <string.h>\n"));
    emit(cg, strada_new_str("#include <stdint.h>\n"));
    emit(cg, strada_new_str("#include <stdbool.h>\n\n"));
    StradaValue *funcs = strada_hash_get(strada_deref_hash(program), strada_to_str(strada_new_str("functions")));
    StradaValue *i = strada_new_int(0);
    while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(strada_hash_get(strada_deref_hash(program), strada_to_str(strada_new_str("function_count"))))))) {
        StradaValue *fn = strada_array_get(strada_deref_array(funcs), strada_to_int(i));
        StradaValue *name = strada_hash_get(strada_deref_hash(fn), strada_to_str(strada_new_str("name")));
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(name), strada_to_str(strada_new_str("main"))) == 0))) {
            emit(cg, strada_new_str("int main(void);\n"));
        } else {
            emit(cg, strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(type_to_c(strada_hash_get(strada_deref_hash(fn), strada_to_str(strada_new_str("return_type"))))), strada_to_str(strada_new_str(" "))))), strada_to_str(name)))), strada_to_str(strada_new_str("(")))));
            StradaValue *params = strada_hash_get(strada_deref_hash(fn), strada_to_str(strada_new_str("params")));
            StradaValue *j = strada_new_int(0);
            while (strada_to_bool(strada_new_int(strada_to_num(j) < strada_to_num(strada_hash_get(strada_deref_hash(fn), strada_to_str(strada_new_str("param_count"))))))) {
                if (strada_to_bool(strada_new_int(strada_to_num(j) > strada_to_num(strada_new_int(0))))) {
                    emit(cg, strada_new_str(", "));
                }
                StradaValue *param = strada_array_get(strada_deref_array(params), strada_to_int(j));
                emit(cg, strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(type_to_c(strada_hash_get(strada_deref_hash(param), strada_to_str(strada_new_str("param_type"))))), strada_to_str(strada_new_str(" "))))), strada_to_str(strada_hash_get(strada_deref_hash(param), strada_to_str(strada_new_str("name")))))));
                j = strada_new_num(strada_to_num(j) + strada_to_num(strada_new_int(1)));
            }
            if (strada_to_bool(strada_new_int(strada_to_num(strada_hash_get(strada_deref_hash(fn), strada_to_str(strada_new_str("param_count")))) == strada_to_num(strada_new_int(0))))) {
                emit(cg, strada_new_str("void"));
            }
            emit(cg, strada_new_str(");\n"));
        }
        i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
    }
    emit(cg, strada_new_str("\n"));
    i = strada_new_int(0);
    while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(strada_hash_get(strada_deref_hash(program), strada_to_str(strada_new_str("function_count"))))))) {
        gen_function(cg, strada_array_get(strada_deref_array(funcs), strada_to_int(i)));
        i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
    }
}

StradaValue* generate(StradaValue* ast) {
    StradaValue *cg = codegen_new();
    gen_program(cg, ast);
    return strada_hash_get(strada_deref_hash(cg), strada_to_str(strada_new_str("output")));
}

