/*
 * This file is part of the Strada Language (https://github.com/mjflick/strada-lang).
 * Copyright (c) 2026 Michael J. Flickinger
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 2.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* Generated by Strada Bootstrap Compiler */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

/* @INC paths: */
/*   lib */

StradaValue* lex_new(StradaValue* source);
StradaValue* lex_current_char(StradaValue* lexer);
void lex_advance(StradaValue* lexer);
void lex_skip_whitespace(StradaValue* lexer);
void lex_skip_comment(StradaValue* lexer);
StradaValue* lex_read_identifier(StradaValue* lexer);
StradaValue* lex_read_number(StradaValue* lexer);
StradaValue* lex_read_string(StradaValue* lexer);
StradaValue* lex_keyword_or_ident(StradaValue* text);
StradaValue* lex_next_token(StradaValue* lexer);
StradaValue* lex_tokenize(StradaValue* source);

StradaValue* lex_new(StradaValue* source) {
    StradaValue *lexer = strada_hash_new();
    strada_hash_set(lexer->value.hv, strada_to_str(strada_new_str("source")), source);
    strada_hash_set(lexer->value.hv, strada_to_str(strada_new_str("pos")), strada_new_int(0));
    strada_hash_set(lexer->value.hv, strada_to_str(strada_new_str("line")), strada_new_int(1));
    strada_hash_set(lexer->value.hv, strada_to_str(strada_new_str("column")), strada_new_int(1));
    strada_hash_set(lexer->value.hv, strada_to_str(strada_new_str("length")), strada_new_int(strada_length(strada_to_str(source))));
    return strada_new_ref(lexer, '%');
}

StradaValue* lex_current_char(StradaValue* lexer) {
    StradaValue *pos = strada_hash_get(strada_deref_hash(lexer), strada_to_str(strada_new_str("pos")));
    StradaValue *len = strada_hash_get(strada_deref_hash(lexer), strada_to_str(strada_new_str("length")));
    if (strada_to_bool(strada_new_int(strada_to_num(pos) >= strada_to_num(len)))) {
        return strada_new_str("");
    }
    StradaValue *source = strada_hash_get(strada_deref_hash(lexer), strada_to_str(strada_new_str("source")));
    return strada_substr(source, strada_to_int(pos), strada_to_int(strada_new_int(1)));
}

void lex_advance(StradaValue* lexer) {
    StradaValue *ch = lex_current_char(lexer);
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("\n"))) == 0))) {
        strada_hash_set(strada_deref_hash(lexer), strada_to_str(strada_new_str("line")), strada_new_num(strada_to_num(strada_hash_get(strada_deref_hash(lexer), strada_to_str(strada_new_str("line")))) + strada_to_num(strada_new_int(1))));
        strada_hash_set(strada_deref_hash(lexer), strada_to_str(strada_new_str("column")), strada_new_int(1));
    } else {
        strada_hash_set(strada_deref_hash(lexer), strada_to_str(strada_new_str("column")), strada_new_num(strada_to_num(strada_hash_get(strada_deref_hash(lexer), strada_to_str(strada_new_str("column")))) + strada_to_num(strada_new_int(1))));
    }
    strada_hash_set(strada_deref_hash(lexer), strada_to_str(strada_new_str("pos")), strada_new_num(strada_to_num(strada_hash_get(strada_deref_hash(lexer), strada_to_str(strada_new_str("pos")))) + strada_to_num(strada_new_int(1))));
}

void lex_skip_whitespace(StradaValue* lexer) {
    while (strada_to_bool(strada_new_int(1))) {
        StradaValue *ch = lex_current_char(lexer);
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(""))) == 0))) {
            return;
        }
        if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(" "))) == 0)) || strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("\t"))) == 0)))) || strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("\n"))) == 0)))) || strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("\r"))) == 0))))) {
            lex_advance(lexer);
        } else {
            return;
        }
    }
}

void lex_skip_comment(StradaValue* lexer) {
    StradaValue *ch = lex_current_char(lexer);
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("#"))) != 0))) {
        return;
    }
    while (strada_to_bool(strada_new_int(1))) {
        lex_advance(lexer);
        ch = lex_current_char(lexer);
        if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(""))) == 0)) || strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("\n"))) == 0))))) {
            return;
        }
    }
}

StradaValue* lex_read_identifier(StradaValue* lexer) {
    StradaValue *result = strada_new_str("");
    while (strada_to_bool(strada_new_int(1))) {
        StradaValue *ch = lex_current_char(lexer);
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(""))) == 0))) {
            return result;
        }
        if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("a"))) >= 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("z"))) <= 0)))) || strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("A"))) >= 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("Z"))) <= 0)))))) || strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("0"))) >= 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("9"))) <= 0)))))) || strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("_"))) == 0))))) {
            result = strada_new_str(strada_concat(strada_to_str(result), strada_to_str(ch)));
            lex_advance(lexer);
        } else {
            return result;
        }
    }
}

StradaValue* lex_read_number(StradaValue* lexer) {
    StradaValue *result = strada_new_str("");
    StradaValue *is_float = strada_new_int(0);
    while (strada_to_bool(strada_new_int(1))) {
        StradaValue *ch = lex_current_char(lexer);
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(""))) == 0))) {
            StradaValue *token = strada_hash_new();
            if (strada_to_bool(is_float)) {
                strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("NUM_LITERAL"));
            } else {
                strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("INT_LITERAL"));
            }
            strada_hash_set(token->value.hv, strada_to_str(strada_new_str("value")), result);
            return strada_new_ref(token, '%');
        }
        if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("0"))) >= 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("9"))) <= 0))))) {
            result = strada_new_str(strada_concat(strada_to_str(result), strada_to_str(ch)));
            lex_advance(lexer);
        } else if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("."))) == 0)) && strada_to_bool(strada_new_int(strada_to_num(is_float) == strada_to_num(strada_new_int(0))))))) {
            is_float = strada_new_int(1);
            result = strada_new_str(strada_concat(strada_to_str(result), strada_to_str(ch)));
            lex_advance(lexer);
        } else {
            StradaValue *token = strada_hash_new();
            if (strada_to_bool(is_float)) {
                strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("NUM_LITERAL"));
            } else {
                strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("INT_LITERAL"));
            }
            strada_hash_set(token->value.hv, strada_to_str(strada_new_str("value")), result);
            return strada_new_ref(token, '%');
        }
    }
}

StradaValue* lex_read_string(StradaValue* lexer) {
    StradaValue *quote = lex_current_char(lexer);
    lex_advance(lexer);
    StradaValue *result = strada_new_str("");
    while (strada_to_bool(strada_new_int(1))) {
        StradaValue *ch = lex_current_char(lexer);
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(""))) == 0))) {
            die(strada_new_str("Unterminated string"));
        }
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(quote)) == 0))) {
            lex_advance(lexer);
            return result;
        }
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("\\"))) == 0))) {
            lex_advance(lexer);
            StradaValue *nextch = lex_current_char(lexer);
            if (strada_to_bool(strada_new_int(strcmp(strada_to_str(nextch), strada_to_str(strada_new_str("n"))) == 0))) {
                result = strada_new_str(strada_concat(strada_to_str(result), strada_to_str(strada_new_str("\n"))));
            } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(nextch), strada_to_str(strada_new_str("t"))) == 0))) {
                result = strada_new_str(strada_concat(strada_to_str(result), strada_to_str(strada_new_str("\t"))));
            } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(nextch), strada_to_str(strada_new_str("\\"))) == 0))) {
                result = strada_new_str(strada_concat(strada_to_str(result), strada_to_str(strada_new_str("\\"))));
            } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(nextch), strada_to_str(quote)) == 0))) {
                result = strada_new_str(strada_concat(strada_to_str(result), strada_to_str(quote)));
            } else {
                result = strada_new_str(strada_concat(strada_to_str(result), strada_to_str(nextch)));
            }
            lex_advance(lexer);
        } else {
            result = strada_new_str(strada_concat(strada_to_str(result), strada_to_str(ch)));
            lex_advance(lexer);
        }
    }
}

StradaValue* lex_keyword_or_ident(StradaValue* text) {
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("func"))) == 0))) {
        return strada_new_str("FUNC");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("my"))) == 0))) {
        return strada_new_str("MY");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("if"))) == 0))) {
        return strada_new_str("IF");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("elsif"))) == 0))) {
        return strada_new_str("ELSIF");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("else"))) == 0))) {
        return strada_new_str("ELSE");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("while"))) == 0))) {
        return strada_new_str("WHILE");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("for"))) == 0))) {
        return strada_new_str("FOR");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("foreach"))) == 0))) {
        return strada_new_str("FOREACH");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("return"))) == 0))) {
        return strada_new_str("RETURN");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("last"))) == 0))) {
        return strada_new_str("LAST");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("next"))) == 0))) {
        return strada_new_str("NEXT");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("int"))) == 0))) {
        return strada_new_str("TYPE_INT");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("num"))) == 0))) {
        return strada_new_str("TYPE_NUM");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("str"))) == 0))) {
        return strada_new_str("TYPE_STR");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("array"))) == 0))) {
        return strada_new_str("TYPE_ARRAY");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("hash"))) == 0))) {
        return strada_new_str("TYPE_HASH");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("scalar"))) == 0))) {
        return strada_new_str("TYPE_SCALAR");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("void"))) == 0))) {
        return strada_new_str("TYPE_VOID");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("undef"))) == 0))) {
        return strada_new_str("UNDEF");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("defined"))) == 0))) {
        return strada_new_str("DEFINED");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("ref"))) == 0))) {
        return strada_new_str("REF");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("dump"))) == 0))) {
        return strada_new_str("DUMP");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("dumper"))) == 0))) {
        return strada_new_str("DUMPER");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("say"))) == 0))) {
        return strada_new_str("SAY");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("print"))) == 0))) {
        return strada_new_str("PRINT");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("die"))) == 0))) {
        return strada_new_str("DIE");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("push"))) == 0))) {
        return strada_new_str("PUSH");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("pop"))) == 0))) {
        return strada_new_str("POP");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("shift"))) == 0))) {
        return strada_new_str("SHIFT");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("unshift"))) == 0))) {
        return strada_new_str("UNSHIFT");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("scalar"))) == 0))) {
        return strada_new_str("SCALAR");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("length"))) == 0))) {
        return strada_new_str("LENGTH");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(text), strada_to_str(strada_new_str("substr"))) == 0))) {
        return strada_new_str("SUBSTR");
    }
    return strada_new_str("IDENT");
}

StradaValue* lex_next_token(StradaValue* lexer) {
    lex_skip_whitespace(lexer);
    StradaValue *ch = lex_current_char(lexer);
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(""))) == 0))) {
        StradaValue *token = strada_hash_new();
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("EOF"));
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("value")), strada_new_str(""));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("#"))) == 0))) {
        lex_skip_comment(lexer);
        return lex_next_token(lexer);
    }
    if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("a"))) >= 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("z"))) <= 0)))) || strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("A"))) >= 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("Z"))) <= 0)))))) || strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("_"))) == 0))))) {
        StradaValue *text = lex_read_identifier(lexer);
        StradaValue *type = lex_keyword_or_ident(text);
        StradaValue *token = strada_hash_new();
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), type);
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("value")), text);
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("0"))) >= 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("9"))) <= 0))))) {
        return lex_read_number(lexer);
    }
    if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("\""))) == 0)) || strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("'"))) == 0))))) {
        StradaValue *str_val = lex_read_string(lexer);
        StradaValue *token = strada_hash_new();
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("STR_LITERAL"));
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("value")), str_val);
        return strada_new_ref(token, '%');
    }
    StradaValue *ch2 = strada_substr(strada_hash_get(strada_deref_hash(lexer), strada_to_str(strada_new_str("source"))), strada_to_int(strada_hash_get(strada_deref_hash(lexer), strada_to_str(strada_new_str("pos")))), strada_to_int(strada_new_int(2)));
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch2), strada_to_str(strada_new_str("=="))) == 0))) {
        lex_advance(lexer);
        lex_advance(lexer);
        StradaValue *token = strada_hash_new();
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("EQ"));
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("value")), strada_new_str("=="));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch2), strada_to_str(strada_new_str("!="))) == 0))) {
        lex_advance(lexer);
        lex_advance(lexer);
        StradaValue *token = strada_hash_new();
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("NE"));
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("value")), strada_new_str("!="));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch2), strada_to_str(strada_new_str("<="))) == 0))) {
        lex_advance(lexer);
        lex_advance(lexer);
        StradaValue *token = strada_hash_new();
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("LE"));
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("value")), strada_new_str("<="));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch2), strada_to_str(strada_new_str(">="))) == 0))) {
        lex_advance(lexer);
        lex_advance(lexer);
        StradaValue *token = strada_hash_new();
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("GE"));
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("value")), strada_new_str(">="));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch2), strada_to_str(strada_new_str("&&"))) == 0))) {
        lex_advance(lexer);
        lex_advance(lexer);
        StradaValue *token = strada_hash_new();
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("AND"));
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("value")), strada_new_str("&&"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch2), strada_to_str(strada_new_str("||"))) == 0))) {
        lex_advance(lexer);
        lex_advance(lexer);
        StradaValue *token = strada_hash_new();
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("OR"));
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("value")), strada_new_str("||"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch2), strada_to_str(strada_new_str("->"))) == 0))) {
        lex_advance(lexer);
        lex_advance(lexer);
        StradaValue *token = strada_hash_new();
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("ARROW"));
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("value")), strada_new_str("->"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch2), strada_to_str(strada_new_str("=>"))) == 0))) {
        lex_advance(lexer);
        lex_advance(lexer);
        StradaValue *token = strada_hash_new();
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("FAT_ARROW"));
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("value")), strada_new_str("=>"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch2), strada_to_str(strada_new_str("+="))) == 0))) {
        lex_advance(lexer);
        lex_advance(lexer);
        StradaValue *token = strada_hash_new();
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("PLUS_ASSIGN"));
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("value")), strada_new_str("+="));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch2), strada_to_str(strada_new_str("-="))) == 0))) {
        lex_advance(lexer);
        lex_advance(lexer);
        StradaValue *token = strada_hash_new();
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("MINUS_ASSIGN"));
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("value")), strada_new_str("-="));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch2), strada_to_str(strada_new_str(".="))) == 0))) {
        lex_advance(lexer);
        lex_advance(lexer);
        StradaValue *token = strada_hash_new();
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("DOT_ASSIGN"));
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("value")), strada_new_str(".="));
        return strada_new_ref(token, '%');
    }
    lex_advance(lexer);
    StradaValue *token = strada_hash_new();
    strada_hash_set(token->value.hv, strada_to_str(strada_new_str("value")), ch);
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("("))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("LPAREN"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(")"))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("RPAREN"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("{"))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("LBRACE"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("}"))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("RBRACE"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("["))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("LBRACKET"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("]"))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("RBRACKET"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(";"))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("SEMI"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(","))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("COMMA"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("$"))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("DOLLAR"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("@"))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("AT"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("%"))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("PERCENT"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("+"))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("PLUS"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("-"))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("MINUS"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("*"))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("MULT"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("/"))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("DIV"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("%"))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("MOD"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("."))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("DOT"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("="))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("ASSIGN"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("<"))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("LT"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(">"))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("GT"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("!"))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("NOT"));
        return strada_new_ref(token, '%');
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("\\"))) == 0))) {
        strada_hash_set(token->value.hv, strada_to_str(strada_new_str("type")), strada_new_str("BACKSLASH"));
        return strada_new_ref(token, '%');
    }
    die(strada_new_str(strada_concat(strada_to_str(strada_new_str("Unexpected character: ")), strada_to_str(ch))));
}

StradaValue* lex_tokenize(StradaValue* source) {
    StradaValue *lexer = lex_new(source);
    StradaValue *tokens = strada_hash_new();
    while (strada_to_bool(strada_new_int(1))) {
        StradaValue *token = lex_next_token(lexer);
        (strada_array_push(tokens->value.av, token), strada_new_undef());
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_hash_get(strada_deref_hash(token), strada_to_str(strada_new_str("type")))), strada_to_str(strada_new_str("EOF"))) == 0))) {
            return strada_new_ref(tokens, '@');
        }
    }
}

