/* Generated by Strada Bootstrap Compiler */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

/* @INC paths: */
/*   lib */

StradaValue* read_file(StradaValue* filename);
void write_file(StradaValue* filename, StradaValue* content);
StradaValue* compile(StradaValue* source);
void print_usage(void);
void print_version(void);
int main(void);

StradaValue* read_file(StradaValue* filename) {
    return strada_slurp(strada_to_str(filename));
}

void write_file(StradaValue* filename, StradaValue* content) {
    strada_spew(strada_to_str(filename), strada_to_str(content));
}

StradaValue* compile(StradaValue* source) {
    StradaValue *tokens = lex_tokenize(source);
    StradaValue *ast = parse(tokens);
    StradaValue *code = generate(ast);
    return code;
}

void print_usage(void) {
    strada_say(strada_new_str("Strada Compiler (Self-Hosting)"));
    strada_say(strada_new_str("Usage: stradac <input.strada> <output.c>"));
    strada_say(strada_new_str(""));
    strada_say(strada_new_str("Options:"));
    strada_say(strada_new_str("  -h, --help    Show this help message"));
    strada_say(strada_new_str("  -v, --version Show version information"));
}

void print_version(void) {
    strada_say(strada_new_str("Strada Compiler v1.0.0 (Self-Hosting)"));
    strada_say(strada_new_str("Written in Strada, compiled by bootstrap compiler"));
}

int main(void) {
    strada_say(strada_new_str("Strada Self-Hosting Compiler"));
    strada_say(strada_new_str("============================"));
    strada_say(strada_new_str(""));
    StradaValue *test_source = strada_new_str("func main() int {\n    my str $msg = \"Hello from self-hosted Strada!\";\n    say($msg);\n    \n    my int $x = 10;\n    my int $y = 20;\n    my int $sum = $x + $y;\n    say(\"Sum: \" . $sum);\n    \n    return 0;\n}");
    strada_say(strada_new_str("Input program:"));
    strada_say(strada_new_str("─────────────────────────────────────"));
    strada_say(test_source);
    strada_say(strada_new_str("─────────────────────────────────────"));
    strada_say(strada_new_str(""));
    strada_say(strada_new_str("Compiling..."));
    StradaValue *output = compile(test_source);
    strada_say(strada_new_str(""));
    strada_say(strada_new_str("Generated C code:"));
    strada_say(strada_new_str("═════════════════════════════════════"));
    strada_say(output);
    strada_say(strada_new_str("═════════════════════════════════════"));
    strada_say(strada_new_str(""));
    strada_say(strada_new_str("✓ Compilation successful!"));
    return 0;
}

