/*
 * This file is part of the Strada Language (https://github.com/mjflick/strada-lang).
 * Copyright (c) 2026 Michael J. Flickinger
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 2.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* Generated by Strada Bootstrap Compiler */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

/* @INC paths: */
/*   lib */

StradaValue* parser_new(StradaValue* tokens);
StradaValue* parser_current(StradaValue* parser);
StradaValue* parser_peek(StradaValue* parser);
void parser_advance(StradaValue* parser);
void parser_expect(StradaValue* parser, StradaValue* expected_type);
StradaValue* parser_match(StradaValue* parser, StradaValue* type);
StradaValue* parser_check(StradaValue* parser, StradaValue* type);
StradaValue* parse_type(StradaValue* parser);
StradaValue* parse_primary(StradaValue* parser);
StradaValue* parse_postfix(StradaValue* parser, StradaValue* left);
StradaValue* parse_unary(StradaValue* parser);
StradaValue* parse_multiplicative(StradaValue* parser);
StradaValue* parse_additive(StradaValue* parser);
StradaValue* parse_relational(StradaValue* parser);
StradaValue* parse_equality(StradaValue* parser);
StradaValue* parse_logical_and(StradaValue* parser);
StradaValue* parse_logical_or(StradaValue* parser);
StradaValue* parse_assignment(StradaValue* parser);
StradaValue* parse_expression(StradaValue* parser);
StradaValue* parse_block(StradaValue* parser);
StradaValue* parse_var_decl(StradaValue* parser);
StradaValue* parse_if_stmt(StradaValue* parser);
StradaValue* parse_while_stmt(StradaValue* parser);
StradaValue* parse_for_stmt(StradaValue* parser);
StradaValue* parse_return_stmt(StradaValue* parser);
StradaValue* parse_statement(StradaValue* parser);
StradaValue* parse_function(StradaValue* parser);
StradaValue* parse_program(StradaValue* parser);
StradaValue* parse(StradaValue* tokens);

StradaValue* parser_new(StradaValue* tokens) {
    StradaValue *parser = strada_hash_new();
    strada_hash_set(parser->value.hv, strada_to_str(strada_new_str("tokens")), tokens);
    strada_hash_set(parser->value.hv, strada_to_str(strada_new_str("pos")), strada_new_int(0));
    strada_hash_set(parser->value.hv, strada_to_str(strada_new_str("token_count")), strada_new_int(strada_array_length(tokens->value.av)));
    return strada_new_ref(parser, '%');
}

StradaValue* parser_current(StradaValue* parser) {
    StradaValue *tokens = strada_hash_get(strada_deref_hash(parser), strada_to_str(strada_new_str("tokens")));
    StradaValue *pos = strada_hash_get(strada_deref_hash(parser), strada_to_str(strada_new_str("pos")));
    return strada_array_get(strada_deref_array(tokens), strada_to_int(pos));
}

StradaValue* parser_peek(StradaValue* parser) {
    StradaValue *tokens = strada_hash_get(strada_deref_hash(parser), strada_to_str(strada_new_str("tokens")));
    StradaValue *pos = strada_new_num(strada_to_num(strada_hash_get(strada_deref_hash(parser), strada_to_str(strada_new_str("pos")))) + strada_to_num(strada_new_int(1)));
    if (strada_to_bool(strada_new_int(strada_to_num(pos) >= strada_to_num(strada_hash_get(strada_deref_hash(parser), strada_to_str(strada_new_str("token_count"))))))) {
        return parser_current(parser);
    }
    return strada_array_get(strada_deref_array(tokens), strada_to_int(pos));
}

void parser_advance(StradaValue* parser) {
    if (strada_to_bool(strada_new_int(strada_to_num(strada_hash_get(strada_deref_hash(parser), strada_to_str(strada_new_str("pos")))) < strada_to_num(strada_new_num(strada_to_num(strada_hash_get(strada_deref_hash(parser), strada_to_str(strada_new_str("token_count")))) - strada_to_num(strada_new_int(1))))))) {
        strada_hash_set(strada_deref_hash(parser), strada_to_str(strada_new_str("pos")), strada_new_num(strada_to_num(strada_hash_get(strada_deref_hash(parser), strada_to_str(strada_new_str("pos")))) + strada_to_num(strada_new_int(1))));
    }
}

void parser_expect(StradaValue* parser, StradaValue* expected_type) {
    StradaValue *tok = parser_current(parser);
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("type")))), strada_to_str(expected_type)) != 0))) {
        die(strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(strada_new_str("Parse error: expected ")), strada_to_str(expected_type)))), strada_to_str(strada_new_str(", got "))))), strada_to_str(strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("type")))))));
    }
    parser_advance(parser);
}

StradaValue* parser_match(StradaValue* parser, StradaValue* type) {
    StradaValue *tok = parser_current(parser);
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("type")))), strada_to_str(type)) == 0))) {
        parser_advance(parser);
        return 1;
    }
    return 0;
}

StradaValue* parser_check(StradaValue* parser, StradaValue* type) {
    StradaValue *tok = parser_current(parser);
    return strada_new_int(strcmp(strada_to_str(strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("type")))), strada_to_str(type)) == 0);
}

StradaValue* parse_type(StradaValue* parser) {
    StradaValue *tok = parser_current(parser);
    StradaValue *type_str = strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("type")));
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type_str), strada_to_str(strada_new_str("TYPE_INT"))) == 0))) {
        parser_advance(parser);
        return TYPE_INT();
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type_str), strada_to_str(strada_new_str("TYPE_NUM"))) == 0))) {
        parser_advance(parser);
        return TYPE_NUM();
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type_str), strada_to_str(strada_new_str("TYPE_STR"))) == 0))) {
        parser_advance(parser);
        return TYPE_STR();
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type_str), strada_to_str(strada_new_str("TYPE_ARRAY"))) == 0))) {
        parser_advance(parser);
        return TYPE_ARRAY();
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type_str), strada_to_str(strada_new_str("TYPE_HASH"))) == 0))) {
        parser_advance(parser);
        return TYPE_HASH();
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type_str), strada_to_str(strada_new_str("TYPE_SCALAR"))) == 0))) {
        parser_advance(parser);
        return TYPE_SCALAR();
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type_str), strada_to_str(strada_new_str("TYPE_VOID"))) == 0))) {
        parser_advance(parser);
        return TYPE_VOID();
    }
    die(strada_new_str(strada_concat(strada_to_str(strada_new_str("Expected type, got ")), strada_to_str(type_str))));
}

StradaValue* parse_primary(StradaValue* parser) {
    StradaValue *tok = parser_current(parser);
    StradaValue *type = strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("type")));
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("INT_LITERAL"))) == 0))) {
        parser_advance(parser);
        return ast_new_int_literal(strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("value"))));
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("NUM_LITERAL"))) == 0))) {
        parser_advance(parser);
        return ast_new_num_literal(strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("value"))));
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("STR_LITERAL"))) == 0))) {
        parser_advance(parser);
        return ast_new_str_literal(strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("value"))));
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("DOLLAR"))) == 0))) {
        parser_advance(parser);
        StradaValue *name_tok = parser_current(parser);
        parser_expect(parser, strada_new_str("IDENT"));
        StradaValue *var_name = strada_hash_get(strada_deref_hash(name_tok), strada_to_str(strada_new_str("value")));
        if (strada_to_bool(parser_check(parser, strada_new_str("ARROW")))) {
            StradaValue *var = ast_new_variable(var_name, strada_new_str("$"));
            return parse_postfix(parser, var);
        }
        if (strada_to_bool(parser_check(parser, strada_new_str("LBRACE")))) {
            parser_advance(parser);
            StradaValue *key = parse_expression(parser);
            parser_expect(parser, strada_new_str("RBRACE"));
            StradaValue *var = ast_new_variable(var_name, strada_new_str("$"));
            return ast_new_hash_access(var, key);
        }
        if (strada_to_bool(parser_check(parser, strada_new_str("LBRACKET")))) {
            parser_advance(parser);
            StradaValue *idx = parse_expression(parser);
            parser_expect(parser, strada_new_str("RBRACKET"));
            StradaValue *var = ast_new_variable(var_name, strada_new_str("$"));
            return ast_new_subscript(var, idx);
        }
        return ast_new_variable(var_name, strada_new_str("$"));
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("AT"))) == 0))) {
        parser_advance(parser);
        StradaValue *name_tok = parser_current(parser);
        parser_expect(parser, strada_new_str("IDENT"));
        return ast_new_variable(strada_hash_get(strada_deref_hash(name_tok), strada_to_str(strada_new_str("value"))), strada_new_str("@"));
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("PERCENT"))) == 0))) {
        parser_advance(parser);
        StradaValue *name_tok = parser_current(parser);
        parser_expect(parser, strada_new_str("IDENT"));
        return ast_new_variable(strada_hash_get(strada_deref_hash(name_tok), strada_to_str(strada_new_str("value"))), strada_new_str("%"));
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("BACKSLASH"))) == 0))) {
        parser_advance(parser);
        StradaValue *target = parse_primary(parser);
        StradaValue *ref_type = strada_new_str("$");
        if (strada_to_bool(strada_new_int(strada_to_num(strada_hash_get(strada_deref_hash(target), strada_to_str(strada_new_str("type")))) == strada_to_num(NODE_VARIABLE())))) {
            ref_type = strada_hash_get(strada_deref_hash(target), strada_to_str(strada_new_str("sigil")));
        }
        return ast_new_ref(target, ref_type);
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("LBRACE"))) == 0))) {
        parser_advance(parser);
        StradaValue *anon = ast_new_anon_hash();
        if (strada_to_bool(parser_check(parser, strada_new_str("RBRACE")))) {
            parser_advance(parser);
            return anon;
        }
        while (strada_to_bool(strada_new_int(1))) {
            StradaValue *key_tok = parser_current(parser);
            StradaValue *key = strada_new_str("");
            if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_hash_get(strada_deref_hash(key_tok), strada_to_str(strada_new_str("type")))), strada_to_str(strada_new_str("STR_LITERAL"))) == 0)) || strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_hash_get(strada_deref_hash(key_tok), strada_to_str(strada_new_str("type")))), strada_to_str(strada_new_str("IDENT"))) == 0))))) {
                key = strada_hash_get(strada_deref_hash(key_tok), strada_to_str(strada_new_str("value")));
                parser_advance(parser);
            } else {
                die(strada_new_str("Expected hash key"));
            }
            parser_expect(parser, strada_new_str("FAT_ARROW"));
            StradaValue *value = parse_expression(parser);
            ast_add_hash_pair(anon, key, value);
            if (strada_to_bool(parser_check(parser, strada_new_str("COMMA")))) {
                parser_advance(parser);
                if (strada_to_bool(parser_check(parser, strada_new_str("RBRACE")))) {
                    parser_advance(parser);
                    return anon;
                }
            } else {
                parser_expect(parser, strada_new_str("RBRACE"));
                return anon;
            }
        }
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("LBRACKET"))) == 0))) {
        parser_advance(parser);
        StradaValue *anon = ast_new_anon_array();
        if (strada_to_bool(parser_check(parser, strada_new_str("RBRACKET")))) {
            parser_advance(parser);
            return anon;
        }
        while (strada_to_bool(strada_new_int(1))) {
            StradaValue *elem = parse_expression(parser);
            ast_add_array_elem(anon, elem);
            if (strada_to_bool(parser_check(parser, strada_new_str("COMMA")))) {
                parser_advance(parser);
                if (strada_to_bool(parser_check(parser, strada_new_str("RBRACKET")))) {
                    parser_advance(parser);
                    return anon;
                }
            } else {
                parser_expect(parser, strada_new_str("RBRACKET"));
                return anon;
            }
        }
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("LPAREN"))) == 0))) {
        parser_advance(parser);
        if (strada_to_bool(parser_check(parser, strada_new_str("RPAREN")))) {
            parser_advance(parser);
            return ast_new_anon_hash();
        }
        StradaValue *expr = parse_expression(parser);
        parser_expect(parser, strada_new_str("RPAREN"));
        return expr;
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("IDENT"))) == 0))) {
        StradaValue *name = strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("value")));
        parser_advance(parser);
        if (strada_to_bool(parser_check(parser, strada_new_str("LPAREN")))) {
            parser_advance(parser);
            StradaValue *call = ast_new_call(name);
            if (strada_to_bool(strada_new_int(!strada_to_bool(parser_check(parser, strada_new_str("RPAREN")))))) {
                while (strada_to_bool(strada_new_int(1))) {
                    StradaValue *arg = parse_expression(parser);
                    ast_add_arg(call, arg);
                    if (strada_to_bool(parser_check(parser, strada_new_str("COMMA")))) {
                        parser_advance(parser);
                    } else {
                        parser_expect(parser, strada_new_str("RPAREN"));
                        return call;
                    }
                }
            }
            parser_expect(parser, strada_new_str("RPAREN"));
            return call;
        }
        return ast_new_str_literal(name);
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("MINUS"))) == 0))) {
        parser_advance(parser);
        StradaValue *operand = parse_unary(parser);
        return ast_new_unary_op(strada_new_str("-"), operand);
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("NOT"))) == 0))) {
        parser_advance(parser);
        StradaValue *operand = parse_unary(parser);
        return ast_new_unary_op(strada_new_str("!"), operand);
    }
    die(strada_new_str(strada_concat(strada_to_str(strada_new_str("Unexpected token in expression: ")), strada_to_str(type))));
}

StradaValue* parse_postfix(StradaValue* parser, StradaValue* left) {
    while (strada_to_bool(strada_new_int(1))) {
        if (strada_to_bool(parser_check(parser, strada_new_str("ARROW")))) {
            parser_advance(parser);
            if (strada_to_bool(parser_check(parser, strada_new_str("LBRACE")))) {
                parser_advance(parser);
                StradaValue *key = parse_expression(parser);
                parser_expect(parser, strada_new_str("RBRACE"));
                left = ast_new_deref_hash(left, key);
            } else if (strada_to_bool(parser_check(parser, strada_new_str("LBRACKET")))) {
                parser_advance(parser);
                StradaValue *idx = parse_expression(parser);
                parser_expect(parser, strada_new_str("RBRACKET"));
                left = ast_new_deref_array(left, idx);
            } else {
                die(strada_new_str("Expected { or [ after ->"));
            }
        } else if (strada_to_bool(parser_check(parser, strada_new_str("LBRACE")))) {
            parser_advance(parser);
            StradaValue *key = parse_expression(parser);
            parser_expect(parser, strada_new_str("RBRACE"));
            left = ast_new_hash_access(left, key);
        } else if (strada_to_bool(parser_check(parser, strada_new_str("LBRACKET")))) {
            parser_advance(parser);
            StradaValue *idx = parse_expression(parser);
            parser_expect(parser, strada_new_str("RBRACKET"));
            left = ast_new_subscript(left, idx);
        } else {
            return left;
        }
    }
}

StradaValue* parse_unary(StradaValue* parser) {
    StradaValue *tok = parser_current(parser);
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("type")))), strada_to_str(strada_new_str("MINUS"))) == 0))) {
        parser_advance(parser);
        StradaValue *operand = parse_unary(parser);
        return ast_new_unary_op(strada_new_str("-"), operand);
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("type")))), strada_to_str(strada_new_str("NOT"))) == 0))) {
        parser_advance(parser);
        StradaValue *operand = parse_unary(parser);
        return ast_new_unary_op(strada_new_str("!"), operand);
    }
    StradaValue *primary = parse_primary(parser);
    return parse_postfix(parser, primary);
}

StradaValue* parse_multiplicative(StradaValue* parser) {
    StradaValue *left = parse_unary(parser);
    while (strada_to_bool(strada_new_int(1))) {
        StradaValue *tok = parser_current(parser);
        StradaValue *type = strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("type")));
        if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("MULT"))) == 0)) || strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("DIV"))) == 0)))) || strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("MOD"))) == 0))))) {
            StradaValue *op = strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("value")));
            parser_advance(parser);
            StradaValue *right = parse_unary(parser);
            left = ast_new_binary_op(op, left, right);
        } else {
            return left;
        }
    }
}

StradaValue* parse_additive(StradaValue* parser) {
    StradaValue *left = parse_multiplicative(parser);
    while (strada_to_bool(strada_new_int(1))) {
        StradaValue *tok = parser_current(parser);
        StradaValue *type = strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("type")));
        if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("PLUS"))) == 0)) || strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("MINUS"))) == 0)))) || strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("DOT"))) == 0))))) {
            StradaValue *op = strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("value")));
            parser_advance(parser);
            StradaValue *right = parse_multiplicative(parser);
            left = ast_new_binary_op(op, left, right);
        } else {
            return left;
        }
    }
}

StradaValue* parse_relational(StradaValue* parser) {
    StradaValue *left = parse_additive(parser);
    while (strada_to_bool(strada_new_int(1))) {
        StradaValue *tok = parser_current(parser);
        StradaValue *type = strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("type")));
        if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("LT"))) == 0)) || strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("GT"))) == 0)))) || strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("LE"))) == 0)))) || strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("GE"))) == 0))))) {
            StradaValue *op = strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("value")));
            parser_advance(parser);
            StradaValue *right = parse_additive(parser);
            left = ast_new_binary_op(op, left, right);
        } else {
            return left;
        }
    }
}

StradaValue* parse_equality(StradaValue* parser) {
    StradaValue *left = parse_relational(parser);
    while (strada_to_bool(strada_new_int(1))) {
        StradaValue *tok = parser_current(parser);
        StradaValue *type = strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("type")));
        if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("EQ"))) == 0)) || strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("NE"))) == 0))))) {
            StradaValue *op = strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("value")));
            parser_advance(parser);
            StradaValue *right = parse_relational(parser);
            left = ast_new_binary_op(op, left, right);
        } else {
            return left;
        }
    }
}

StradaValue* parse_logical_and(StradaValue* parser) {
    StradaValue *left = parse_equality(parser);
    while (strada_to_bool(parser_check(parser, strada_new_str("AND")))) {
        parser_advance(parser);
        StradaValue *right = parse_equality(parser);
        left = ast_new_binary_op(strada_new_str("&&"), left, right);
    }
    return left;
}

StradaValue* parse_logical_or(StradaValue* parser) {
    StradaValue *left = parse_logical_and(parser);
    while (strada_to_bool(parser_check(parser, strada_new_str("OR")))) {
        parser_advance(parser);
        StradaValue *right = parse_logical_and(parser);
        left = ast_new_binary_op(strada_new_str("||"), left, right);
    }
    return left;
}

StradaValue* parse_assignment(StradaValue* parser) {
    StradaValue *left = parse_logical_or(parser);
    StradaValue *tok = parser_current(parser);
    StradaValue *type = strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("type")));
    if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("ASSIGN"))) == 0)) || strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("PLUS_ASSIGN"))) == 0)))) || strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("MINUS_ASSIGN"))) == 0)))) || strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("DOT_ASSIGN"))) == 0))))) {
        StradaValue *op = strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("value")));
        parser_advance(parser);
        StradaValue *right = parse_assignment(parser);
        return ast_new_assign(op, left, right);
    }
    return left;
}

StradaValue* parse_expression(StradaValue* parser) {
    return parse_assignment(parser);
}

StradaValue* parse_block(StradaValue* parser) {
    parser_expect(parser, strada_new_str("LBRACE"));
    StradaValue *block = ast_new_block();
    while (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(!strada_to_bool(parser_check(parser, strada_new_str("RBRACE"))))) && strada_to_bool(strada_new_int(!strada_to_bool(parser_check(parser, strada_new_str("EOF")))))))) {
        StradaValue *stmt = parse_statement(parser);
        ast_add_statement(block, stmt);
    }
    parser_expect(parser, strada_new_str("RBRACE"));
    return block;
}

StradaValue* parse_var_decl(StradaValue* parser) {
    parser_expect(parser, strada_new_str("MY"));
    StradaValue *var_type = parse_type(parser);
    StradaValue *sigil_tok = parser_current(parser);
    StradaValue *sigil = strada_new_str("$");
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_hash_get(strada_deref_hash(sigil_tok), strada_to_str(strada_new_str("type")))), strada_to_str(strada_new_str("DOLLAR"))) == 0))) {
        sigil = strada_new_str("$");
        parser_advance(parser);
    } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_hash_get(strada_deref_hash(sigil_tok), strada_to_str(strada_new_str("type")))), strada_to_str(strada_new_str("AT"))) == 0))) {
        sigil = strada_new_str("@");
        parser_advance(parser);
    } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_hash_get(strada_deref_hash(sigil_tok), strada_to_str(strada_new_str("type")))), strada_to_str(strada_new_str("PERCENT"))) == 0))) {
        sigil = strada_new_str("%");
        parser_advance(parser);
    }
    StradaValue *name_tok = parser_current(parser);
    parser_expect(parser, strada_new_str("IDENT"));
    StradaValue *name = strada_hash_get(strada_deref_hash(name_tok), strada_to_str(strada_new_str("value")));
    StradaValue *decl = ast_new_var_decl(name, var_type, sigil);
    if (strada_to_bool(parser_check(parser, strada_new_str("ASSIGN")))) {
        parser_advance(parser);
        strada_hash_set(strada_deref_hash(decl), strada_to_str(strada_new_str("init")), parse_expression(parser));
    }
    parser_expect(parser, strada_new_str("SEMI"));
    return decl;
}

StradaValue* parse_if_stmt(StradaValue* parser) {
    parser_expect(parser, strada_new_str("IF"));
    parser_expect(parser, strada_new_str("LPAREN"));
    StradaValue *condition = parse_expression(parser);
    parser_expect(parser, strada_new_str("RPAREN"));
    StradaValue *then_block = parse_block(parser);
    StradaValue *if_stmt = ast_new_if_stmt(condition, then_block);
    while (strada_to_bool(parser_check(parser, strada_new_str("ELSIF")))) {
        parser_advance(parser);
        parser_expect(parser, strada_new_str("LPAREN"));
        StradaValue *elsif_cond = parse_expression(parser);
        parser_expect(parser, strada_new_str("RPAREN"));
        StradaValue *elsif_block = parse_block(parser);
        ast_add_elsif(if_stmt, elsif_cond, elsif_block);
    }
    if (strada_to_bool(parser_check(parser, strada_new_str("ELSE")))) {
        parser_advance(parser);
        strada_hash_set(strada_deref_hash(if_stmt), strada_to_str(strada_new_str("else_block")), parse_block(parser));
    }
    return if_stmt;
}

StradaValue* parse_while_stmt(StradaValue* parser) {
    parser_expect(parser, strada_new_str("WHILE"));
    parser_expect(parser, strada_new_str("LPAREN"));
    StradaValue *condition = parse_expression(parser);
    parser_expect(parser, strada_new_str("RPAREN"));
    StradaValue *body = parse_block(parser);
    return ast_new_while_stmt(condition, body);
}

StradaValue* parse_for_stmt(StradaValue* parser) {
    parser_expect(parser, strada_new_str("FOR"));
    parser_expect(parser, strada_new_str("LPAREN"));
    StradaValue *init = strada_new_int(0);
    if (strada_to_bool(parser_check(parser, strada_new_str("MY")))) {
        parser_advance(parser);
        StradaValue *var_type = parse_type(parser);
        StradaValue *sigil_tok = parser_current(parser);
        StradaValue *sigil = strada_new_str("$");
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_hash_get(strada_deref_hash(sigil_tok), strada_to_str(strada_new_str("type")))), strada_to_str(strada_new_str("DOLLAR"))) == 0))) {
            sigil = strada_new_str("$");
            parser_advance(parser);
        }
        StradaValue *name_tok = parser_current(parser);
        parser_expect(parser, strada_new_str("IDENT"));
        init = ast_new_var_decl(strada_hash_get(strada_deref_hash(name_tok), strada_to_str(strada_new_str("value"))), var_type, sigil);
        if (strada_to_bool(parser_check(parser, strada_new_str("ASSIGN")))) {
            parser_advance(parser);
            strada_hash_set(strada_deref_hash(init), strada_to_str(strada_new_str("init")), parse_expression(parser));
        }
    } else if (strada_to_bool(strada_new_int(!strada_to_bool(parser_check(parser, strada_new_str("SEMI")))))) {
        init = parse_expression(parser);
    }
    parser_expect(parser, strada_new_str("SEMI"));
    StradaValue *cond = strada_new_int(0);
    if (strada_to_bool(strada_new_int(!strada_to_bool(parser_check(parser, strada_new_str("SEMI")))))) {
        cond = parse_expression(parser);
    }
    parser_expect(parser, strada_new_str("SEMI"));
    StradaValue *update = strada_new_int(0);
    if (strada_to_bool(strada_new_int(!strada_to_bool(parser_check(parser, strada_new_str("RPAREN")))))) {
        update = parse_expression(parser);
    }
    parser_expect(parser, strada_new_str("RPAREN"));
    StradaValue *body = parse_block(parser);
    return ast_new_for_stmt(init, cond, update, body);
}

StradaValue* parse_return_stmt(StradaValue* parser) {
    parser_expect(parser, strada_new_str("RETURN"));
    StradaValue *value = strada_new_int(0);
    if (strada_to_bool(strada_new_int(!strada_to_bool(parser_check(parser, strada_new_str("SEMI")))))) {
        value = parse_expression(parser);
    }
    parser_expect(parser, strada_new_str("SEMI"));
    return ast_new_return_stmt(value);
}

StradaValue* parse_statement(StradaValue* parser) {
    StradaValue *tok = parser_current(parser);
    StradaValue *type = strada_hash_get(strada_deref_hash(tok), strada_to_str(strada_new_str("type")));
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("MY"))) == 0))) {
        return parse_var_decl(parser);
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("IF"))) == 0))) {
        return parse_if_stmt(parser);
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("WHILE"))) == 0))) {
        return parse_while_stmt(parser);
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("FOR"))) == 0))) {
        return parse_for_stmt(parser);
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("RETURN"))) == 0))) {
        return parse_return_stmt(parser);
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("LAST"))) == 0))) {
        parser_advance(parser);
        parser_expect(parser, strada_new_str("SEMI"));
        StradaValue *node = ast_new_node(strada_new_int(100));
        return node;
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("NEXT"))) == 0))) {
        parser_advance(parser);
        parser_expect(parser, strada_new_str("SEMI"));
        StradaValue *node = ast_new_node(strada_new_int(101));
        return node;
    }
    StradaValue *expr = parse_expression(parser);
    parser_expect(parser, strada_new_str("SEMI"));
    return ast_new_expr_stmt(expr);
}

StradaValue* parse_function(StradaValue* parser) {
    parser_expect(parser, strada_new_str("FUNC"));
    StradaValue *name_tok = parser_current(parser);
    parser_expect(parser, strada_new_str("IDENT"));
    StradaValue *func_name = strada_hash_get(strada_deref_hash(name_tok), strada_to_str(strada_new_str("value")));
    parser_expect(parser, strada_new_str("LPAREN"));
    StradaValue *fn = ast_new_function(func_name, TYPE_VOID());
    if (strada_to_bool(strada_new_int(!strada_to_bool(parser_check(parser, strada_new_str("RPAREN")))))) {
        while (strada_to_bool(strada_new_int(1))) {
            StradaValue *param_type = parse_type(parser);
            StradaValue *sigil_tok = parser_current(parser);
            StradaValue *sigil = strada_new_str("$");
            if (strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_hash_get(strada_deref_hash(sigil_tok), strada_to_str(strada_new_str("type")))), strada_to_str(strada_new_str("DOLLAR"))) == 0))) {
                sigil = strada_new_str("$");
                parser_advance(parser);
            } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_hash_get(strada_deref_hash(sigil_tok), strada_to_str(strada_new_str("type")))), strada_to_str(strada_new_str("AT"))) == 0))) {
                sigil = strada_new_str("@");
                parser_advance(parser);
            } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_hash_get(strada_deref_hash(sigil_tok), strada_to_str(strada_new_str("type")))), strada_to_str(strada_new_str("PERCENT"))) == 0))) {
                sigil = strada_new_str("%");
                parser_advance(parser);
            }
            StradaValue *pname_tok = parser_current(parser);
            parser_expect(parser, strada_new_str("IDENT"));
            StradaValue *param = ast_new_param(strada_hash_get(strada_deref_hash(pname_tok), strada_to_str(strada_new_str("value"))), param_type, sigil);
            ast_add_param(fn, param);
            if (strada_to_bool(parser_check(parser, strada_new_str("COMMA")))) {
                parser_advance(parser);
            } else {
                parser_expect(parser, strada_new_str("RPAREN"));
                break;
            }
        }
    } else {
        parser_advance(parser);
    }
    StradaValue *ret_type = parse_type(parser);
    strada_hash_set(strada_deref_hash(fn), strada_to_str(strada_new_str("return_type")), ret_type);
    strada_hash_set(strada_deref_hash(fn), strada_to_str(strada_new_str("body")), parse_block(parser));
    return fn;
}

StradaValue* parse_program(StradaValue* parser) {
    StradaValue *program = ast_new_program();
    while (strada_to_bool(strada_new_int(!strada_to_bool(parser_check(parser, strada_new_str("EOF")))))) {
        if (strada_to_bool(parser_check(parser, strada_new_str("FUNC")))) {
            StradaValue *fn = parse_function(parser);
            ast_add_function(program, fn);
        } else {
            die(strada_new_str("Expected function definition"));
        }
    }
    return program;
}

StradaValue* parse(StradaValue* tokens) {
    StradaValue *parser = parser_new(tokens);
    return parse_program(parser);
}

